# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Miniflux installation tasks
  block:
    - name: Validate Miniflux configuration
      when: miniflux_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Miniflux
      when: miniflux_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-miniflux
    - install-all
    - install-miniflux

- name: Perform Miniflux uninstallation tasks
  block:
    - name: Uninstall Miniflux
      when: not miniflux_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-miniflux
